apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanogpt-data
  namespace: aic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-rbd
